import { academicCapIcon } from './academic-cap';
import { checkCircleIcon } from './check-circle';
import { documentAddIcon } from './document-add';
import { documentIcon } from './document';
import { downloadIcon } from './download';
import { exclamationCircleIcon } from './exclamation-circle';
import { owlIcon } from './owl';
import { playIcon } from './play';
import { questionMarkCircleIcon } from './question-mark-circle';
import { saveIcon } from './save';
import { uploadIcon } from './upload';
export const code4CodeIcons = [academicCapIcon, checkCircleIcon, documentAddIcon, documentIcon, downloadIcon, exclamationCircleIcon, owlIcon, playIcon, questionMarkCircleIcon, saveIcon, uploadIcon];
